from pathlib import Path
import json
root=Path(__file__).parent
langs=['fil','id','vi','th','es','pt','fr','de','ru'];packs={l:{} for l in langs}
for line in (root/'translations.txt').read_text().splitlines():
    parts=line.split('|');assert len(parts)==10,(len(parts),parts[0])
    for lang,value in zip(langs,parts[1:]):
        assert parts[0] not in packs[lang],parts[0]
        packs[lang][parts[0]]=value
        if parts[0] in ['Community','Updates']:packs[lang][parts[0].upper()]=value
q=lambda x:json.dumps(x,ensure_ascii=False)
core=(root/'i18n-core.lua').read_text();table='I18N.Packs={\n'+''.join('['+q(l)+']={\n'+''.join('['+q(k)+']='+q(v)+',\n' for k,v in p.items())+'},\n' for l,p in packs.items())+'}\n'
core=core.replace('return I18N\n',table+'return I18N\n');(root/'i18n.lua').write_text(core)
s=(root/'../../dist/ui/phonk-v3-1-0.lua').read_text()
s=s.replace('-- SERENITY CONCEPT 02 / ISOLATED UI PREVIEW\n-- Generated by prototype/build.py; edit source modules instead.', '-- SERENITY / PHONK LANGUAGE PREVIEW\n-- UI only. Generated by preview/phonk-language/build.py.')
s=s.replace('local M = {}','local M = {}\nM.I18N=(function()\n'+core+'\nend)()')
s=s.replace("object.Parent=parent; return object", """object.Parent=parent
        if self.Locale and (kind=='TextLabel' or kind=='TextButton' or kind=='TextBox') then
            object.AutoLocalize=false
            if kind=='TextBox' then self.Locale:Bind(object,'PlaceholderText')
            else self.Locale:Bind(object,'Text') end
        end
        return object""")
s=s.replace("TextXAlignment=Enum.TextXAlignment.Left,TextTruncate=Enum.TextTruncate.AtEnd}","TextXAlignment=Enum.TextXAlignment.Left,TextWrapped=true,TextTruncate=Enum.TextTruncate.None}")
s=s.replace("BorderSizePixel=0,AutoButtonColor=false,BackgroundColor3=theme.Inset", "TextWrapped=true,BorderSizePixel=0,AutoButtonColor=false,BackgroundColor3=theme.Inset")
s=s.replace('math.max(height or 44,self.Touch and 48 or 44)','math.max(height or 64,64)')
s=s.replace("local row,label=ui:Row(parent,props.Title)\n        local track", "local row,label=ui:Row(parent,props.Title)\n        label.Size=UDim2.new(1,-82,1,0)\n        local track")
s=s.replace("ui:Row(parent,props.Title,62)","ui:Row(parent,props.Title,80)").replace('label.Size=UDim2.new(0.65,0,0,30)','label.Size=UDim2.new(1,-110,0,48)').replace('UDim2.fromOffset(12,43)','UDim2.fromOffset(12,61)').replace('UDim2.fromOffset(6,31)','UDim2.fromOffset(6,49)')
s=s.replace("local row,label=ui:Row(parent,props.Title,42)\n        local button", "local row,label=ui:Row(parent,props.Title,76)\n        local button")
s=s.replace("summary=ui:Label(button,'',11","summary=ui:Label(button,'',13").replace("ui:Label(item,option,11","ui:Label(item,option,13")
s=s.replace("Text=string.lower(option)","Text=string.lower(option..' '..ui.Locale:T(option))")
s=s.replace("local width=math.max(76,#spec.Id*8+42)","local width=math.max(142,#spec.Id*8+42)")
s=s.replace('local headerHeight=mobile and 44 or 54','local headerHeight=80').replace('title.Size=UDim2.new(1,0,0,23)','title.Size=UDim2.new(1,0,0,32)').replace('description.Position=UDim2.fromOffset(0,30); description.Size=UDim2.new(1,0,0,16); description.TextSize=11','description.Position=UDim2.fromOffset(0,42); description.Size=UDim2.new(1,0,0,34); description.TextSize=12')
s=s.replace("Size=UDim2.new(0,280,0,44),ZIndex=150","Size=UDim2.new(0,280,0,76),ZIndex=150")
s=s.replace('props.Height or 76','math.max(props.Height or 116,116)').replace("props.Title or 'Information',11","props.Title or 'Information',13").replace("UDim2.new(1,-44,0,20)","UDim2.new(1,-44,0,32)").replace("props.Text or '',10,UDim2.fromOffset(34,28),UDim2.new(1,-44,1,-31)","props.Text or '',12,UDim2.fromOffset(34,42),UDim2.new(1,-44,1,-47)")
# Add language preference without changing existing IDs or option values.
s=s.replace("{Id='Accent',Type='Select'", "{Id='Language',Type='Select',Title='Language',Options=M.I18N.Options,Default='Automatic (Roblox)',Effect='Language'},\n                {Id='LanguageHelp',Type='Paragraph',Title='Language preview',Text='Choose a language, or match your Roblox language automatically.',Height=120},\n                {Id='Accent',Type='Select'")
s=s.replace('local ui=M.UI(M.Theme,runtime,M.Icons)',"""local localization=game:GetService('LocalizationService')
    local detected='en'
    pcall(function() detected=localization.RobloxLocaleId end)
    local locale=M.I18N.new(state:Get('Settings.Appearance.Language','Automatic (Roblox)'),detected)
    runtime:OnDestroy(function() locale:Destroy() end)
    pcall(function() runtime:Connect(localization:GetPropertyChangedSignal('RobloxLocaleId'),function() locale:Detect(localization.RobloxLocaleId) end) end)
    local ui=M.UI(M.Theme,runtime,M.Icons)
    ui.Locale=locale""")
s=s.replace("if effect=='Accent' then", "if effect=='Language' then locale:Set(value); popup:Close(true); self:Fit(); self:Notify('Language changed')\n            elseif effect=='Accent' then")
s=s.replace("Text=string.lower(entry.Title..' '..entry.Path)","Text=string.lower(entry.Title..' '..entry.Path..' '..locale:T(entry.Title)..' '..locale:T(entry.Path))")
s=s.replace("Size=UDim2.new(1,-4,0,45)","Size=UDim2.new(1,-4,0,70)").replace("entry.Title,12,UDim2.fromOffset(10,3),UDim2.new(1,-20,0,21)","entry.Title,13,UDim2.fromOffset(10,3),UDim2.new(1,-20,0,32)").replace("entry.Path,9,UDim2.fromOffset(10,24),UDim2.new(1,-20,0,16)","entry.Path,11,UDim2.fromOffset(10,36),UDim2.new(1,-20,0,32)")
# Isolate runtime and settings. Don't destroy live Phonk or send preview feedback.
s=s.replace("local key=options.RuntimeKey or '__SERENITY_PHONK_EVOLUTION_V3'","local key='__SERENITY_PHONK_LANGUAGE_PREVIEW'")
s=s.replace("local preview=env.__SERENITY_PHONK_UI_PREVIEW\n    if preview and type(preview.Destroy)=='function' then preview:Destroy() end\n",'')
s=s.replace("ConfigPath='SerenityHub/ui-phonk-v3-1.json'","ConfigPath='SerenityHub/ui-phonk-language-preview-v1.json'")
s=s.replace("Name='SerenityConcept02',ResetOnSpawn", "Name='SerenityPhonkLanguagePreview',ResetOnSpawn")
s=s.replace("local function submit()\n        if busy then return end", "local function submit()\n        do status.Text='Preview: reports are not sent.';return end\n        if busy then return end")
s=s.replace("configured and 'Sends to Serenity when you press Submit.' or 'Shared reporting is awaiting server setup. Your draft stays here.'", "'Preview: reports are not sent.'")
# Remove unused report destination from the preview bundle.
import re
s=re.sub(r"local defaultEndpoint='https://discord.com/api/webhooks/[^']+'", "local defaultEndpoint=''", s)
s=s.replace("configured and 'Submit report' or 'Reporting unavailable'","'Submit report'")
s=s.replace("'Server Job ID and preview version. No profile settings.'", "'Preview: reports are not sent.'")
s=s.replace("'UI 3.1.0 · September 7, 2026'","'Language preview'").replace("'Phonk release: shared feedback, movable launcher, saved UI preferences and mobile layout.'","'Choose a language, or match your Roblox language automatically.'")
s=s.replace("popup:Message('Header update','• Full-width title bar and accent divider\\n• Clearer sections and larger titles\\n• Report character counter\\n• Shared PC/mobile report destination\\n\\n'..(options.Manifest and 'Connected to the supplied game controls.' or 'Standalone UI demonstration.'))", "popup:Message('Language preview','Choose a language, or match your Roblox language automatically.')")
s=s.replace("app.Version='3.1.0'","app.Version='3.1.0-language-preview'")
(root/'phonk-language-ui.lua').write_text(s)
print('Built',len(packs['fil']),'translation entries × 9 languages plus English;',len(s),'UI characters')
